10 KEY OFF: CLS : COLOR 0, 7: PRINT " ADVENTURE #1  -  HINT #3 "; : COLOR 7, 0: PRINT : PRINT : PRINT : COLOR 15, 0: PRINT "Most movable items found on your journey are to use at a later ADVENTURE point."
15 PRINT : PRINT "Containers can be used for items other than the present contents."; : COLOR 7, 0
20 PRINT : PRINT : PRINT : PRINT : PRINT "This is the last of the hints!  You have the idea now!": LOCATE 24, 75: PRINT "Phil"; : LOCATE 21

